# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-03 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('shiptrader', '0001_initial')]

    operations = [
        migrations.AddField(
            model_name='listing', name='active', field=models.BooleanField(default=True)
        )
    ]
